name: ShopKart Production Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  # ==========================================
  # 1. SECURITY
  # ==========================================

  security:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.security.outputs.result }}
    steps:
      - name: security check
        id: security
        run: |
          echo "result=pass" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - name: build
        run:  |
          echo "build result: ${{ needs.security.outputs.result }}"
          if ["${{ needs.security.outputs.result }}" != "pass"]; then
            echo "build blocked due to security failures"
            exit 1
          fi
          echo "build passed"
  
