name: ShopKart Production Pipeline

'on':
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  docker:
    outputs:
      image_tag: ${{ steps.meta.outputs.image_tag }}
      image_digest: ${{ steps.push.outputs.image_digest }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: generate image tag
        id: meta
        run: |
          IMAGE_TAG="${GITHUB_SHA:0:7}"
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.image_tag }} .
      - name: PUSH IMAGE
        id: push
        run: |
          IMAGE="ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.image_tag }}"
          docker push "$IMAGE"
          digest=$(docker inspect --format='{{index .RepoDigests 0 }}' "$IMAGE" | cut -d'@' -f2)
          echo "image_digest=$digest" >> "$GITHUB_OUTPUT"
          echo "Image_digest=$digest"
  security_scan:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: scan for secrets
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}@${{ needs.docker.outputs.image_digest }}
          severity: CRITICAL
          exit-code: 1
      - name: generate sbom
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}@${{ needs.docker.outputs.image_digest }}
          format: cyclonedx
          output: sbom.json
      - name: upload sbom
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-sbom-${{ needs.docker.outputs.image_tag }}
          path: sbom.json
  sign-image:
    needs: 
      - docker
      - security_scan
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: read
      id-token: write
    steps:
      - name: cosign image
        uses: sigstore/cosign-installer@v3

      - name: login 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: sign image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          IMAGE= "ghcr.io/${{ github.repository }}@${{ needs.docker.outputs.image_digest }}"
          cosign sign --yes "$IMAGE"
  verify-image:
    needs: 
      - docker
      - security_scan
    runs-on: ubuntu-latest
    permissions: 
      packages: read
      id-token: write
    steps:
      - name: cosign verify image
        uses: sigstore/cosign-installer@v3
      - name: login 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: verify image
        run: |
          IMAGE= "ghcr.io/${{ github.repository }}@${{ needs.docker.outputs.image_digest }}"
          cosign verify \
            --certificate-identity-regexp= "https://github.com/${{ github.repository }}/.github/workflows/.*" \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            "$IMAGE"

  staging:
    needs: 
      - security_scan
      - docker
      - sign-image
      - verify-image
    runs-on: ubuntu-latest
    steps:

    - name: Deploy exact verified image
      run: |
        IMAGE="ghcr.io/${{ github.repository }}@${{ needs.docker.outputs.image_digest }}"

        echo "Security passed"
        echo "SBOM generated"
        echo "Image signature verified"
        echo "Deploying exact artifact:"
        echo "$IMAGE"
    